//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotePhoneApp
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://turningpointremotephoneapp.com/", ConfigurationName="RemotePhoneApp.RemotePhoneAppSoap")]
    public interface RemotePhoneAppSoap
    {
        
        // CODEGEN: Parameter 'GetFileResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RemotePhoneApp.GetFileResponse GetFile(RemotePhoneApp.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<RemotePhoneApp.GetFileResponse> GetFileAsync(RemotePhoneApp.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/ValidateLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ValidateLogin(string sUser, string sPassword, string sDeviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/ValidateLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ValidateLoginAsync(string sUser, string sPassword, string sDeviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/ValidateUserActive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ValidateUserActive(string sUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/ValidateUserActive", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ValidateUserActiveAsync(string sUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetCategoriesAndSubcategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCategoriesAndSubcategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetCategoriesAndSubcategories", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCategoriesAndSubcategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetCategoriesAndSubcategoriesCust", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCategoriesAndSubcategoriesCust(string sCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetCategoriesAndSubcategoriesCust", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCategoriesAndSubcategoriesCustAsync(string sCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetOrderHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOrderHistory(string sCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetOrderHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetOrderHistoryAsync(string sCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetBanners", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBanners();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetBanners", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBannersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetItems(string sCust, string sDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetItems", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetItemsAsync(string sCust, string sDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetItemQOH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetItemQOH(string sCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetItemQOH", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetItemQOHAsync(string sCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetItemQOH2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetItemQOH2(string sUser, string sCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetItemQOH2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetItemQOH2Async(string sUser, string sCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/SubmitOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SubmitOrder(string sCustNo, string sPO, string sPaymentMethod, string sCCInfo, string sOrderInfo, string sDeliveryPickup, string sUser, string sNotes, int iHoldForReview, string sOrderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/SubmitOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SubmitOrderAsync(string sCustNo, string sPO, string sPaymentMethod, string sCCInfo, string sOrderInfo, string sDeliveryPickup, string sUser, string sNotes, int iHoldForReview, string sOrderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/SubmitOrder2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SubmitOrder2(string sCustNo, string sPO, string sPaymentMethod, string sCCInfo, string sOrderInfo, string sDeliveryPickup, string sUser, string sNotes, int iHoldForReview, string sOrderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/SubmitOrder2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SubmitOrder2Async(string sCustNo, string sPO, string sPaymentMethod, string sCCInfo, string sOrderInfo, string sDeliveryPickup, string sUser, string sNotes, int iHoldForReview, string sOrderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/SubmitRemoteOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SubmitRemoteOrder(string sCustNo, string sPO, string sOrderInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/SubmitRemoteOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SubmitRemoteOrderAsync(string sCustNo, string sPO, string sOrderInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/SubmitReturn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SubmitReturn(string sCustNo, string sOrderInfo, string sUser, string sNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/SubmitReturn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SubmitReturnAsync(string sCustNo, string sOrderInfo, string sUser, string sNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetSalespersonCustomers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSalespersonCustomers(string sUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetSalespersonCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSalespersonCustomersAsync(string sUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetFlyerItemsPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFlyerItemsPDF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turningpointremotephoneapp.com/GetFlyerItemsPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFlyerItemsPDFAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFile", WrapperNamespace="http://turningpointremotephoneapp.com/", IsWrapped=true)]
    public partial class GetFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://turningpointremotephoneapp.com/", Order=0)]
        public string filename;
        
        public GetFileRequest()
        {
        }
        
        public GetFileRequest(string filename)
        {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileResponse", WrapperNamespace="http://turningpointremotephoneapp.com/", IsWrapped=true)]
    public partial class GetFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://turningpointremotephoneapp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFileResult;
        
        public GetFileResponse()
        {
        }
        
        public GetFileResponse(byte[] GetFileResult)
        {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface RemotePhoneAppSoapChannel : RemotePhoneApp.RemotePhoneAppSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class RemotePhoneAppSoapClient : System.ServiceModel.ClientBase<RemotePhoneApp.RemotePhoneAppSoap>, RemotePhoneApp.RemotePhoneAppSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RemotePhoneAppSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(RemotePhoneAppSoapClient.GetBindingForEndpoint(endpointConfiguration), RemotePhoneAppSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemotePhoneAppSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RemotePhoneAppSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemotePhoneAppSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RemotePhoneAppSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemotePhoneAppSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RemotePhoneApp.GetFileResponse RemotePhoneApp.RemotePhoneAppSoap.GetFile(RemotePhoneApp.GetFileRequest request)
        {
            return base.Channel.GetFile(request);
        }
        
        public byte[] GetFile(string filename)
        {
            RemotePhoneApp.GetFileRequest inValue = new RemotePhoneApp.GetFileRequest();
            inValue.filename = filename;
            RemotePhoneApp.GetFileResponse retVal = ((RemotePhoneApp.RemotePhoneAppSoap)(this)).GetFile(inValue);
            return retVal.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RemotePhoneApp.GetFileResponse> RemotePhoneApp.RemotePhoneAppSoap.GetFileAsync(RemotePhoneApp.GetFileRequest request)
        {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<RemotePhoneApp.GetFileResponse> GetFileAsync(string filename)
        {
            RemotePhoneApp.GetFileRequest inValue = new RemotePhoneApp.GetFileRequest();
            inValue.filename = filename;
            return ((RemotePhoneApp.RemotePhoneAppSoap)(this)).GetFileAsync(inValue);
        }
        
        public string ValidateLogin(string sUser, string sPassword, string sDeviceId)
        {
            return base.Channel.ValidateLogin(sUser, sPassword, sDeviceId);
        }
        
        public System.Threading.Tasks.Task<string> ValidateLoginAsync(string sUser, string sPassword, string sDeviceId)
        {
            return base.Channel.ValidateLoginAsync(sUser, sPassword, sDeviceId);
        }
        
        public string ValidateUserActive(string sUser)
        {
            return base.Channel.ValidateUserActive(sUser);
        }
        
        public System.Threading.Tasks.Task<string> ValidateUserActiveAsync(string sUser)
        {
            return base.Channel.ValidateUserActiveAsync(sUser);
        }
        
        public string GetSettings()
        {
            return base.Channel.GetSettings();
        }
        
        public System.Threading.Tasks.Task<string> GetSettingsAsync()
        {
            return base.Channel.GetSettingsAsync();
        }
        
        public string GetCategoriesAndSubcategories()
        {
            return base.Channel.GetCategoriesAndSubcategories();
        }
        
        public System.Threading.Tasks.Task<string> GetCategoriesAndSubcategoriesAsync()
        {
            return base.Channel.GetCategoriesAndSubcategoriesAsync();
        }
        
        public string GetCategoriesAndSubcategoriesCust(string sCust)
        {
            return base.Channel.GetCategoriesAndSubcategoriesCust(sCust);
        }
        
        public System.Threading.Tasks.Task<string> GetCategoriesAndSubcategoriesCustAsync(string sCust)
        {
            return base.Channel.GetCategoriesAndSubcategoriesCustAsync(sCust);
        }
        
        public string GetOrderHistory(string sCust)
        {
            return base.Channel.GetOrderHistory(sCust);
        }
        
        public System.Threading.Tasks.Task<string> GetOrderHistoryAsync(string sCust)
        {
            return base.Channel.GetOrderHistoryAsync(sCust);
        }
        
        public string GetBanners()
        {
            return base.Channel.GetBanners();
        }
        
        public System.Threading.Tasks.Task<string> GetBannersAsync()
        {
            return base.Channel.GetBannersAsync();
        }
        
        public string GetItems(string sCust, string sDate)
        {
            return base.Channel.GetItems(sCust, sDate);
        }
        
        public System.Threading.Tasks.Task<string> GetItemsAsync(string sCust, string sDate)
        {
            return base.Channel.GetItemsAsync(sCust, sDate);
        }
        
        public string GetItemQOH(string sCust)
        {
            return base.Channel.GetItemQOH(sCust);
        }
        
        public System.Threading.Tasks.Task<string> GetItemQOHAsync(string sCust)
        {
            return base.Channel.GetItemQOHAsync(sCust);
        }
        
        public string GetItemQOH2(string sUser, string sCust)
        {
            return base.Channel.GetItemQOH2(sUser, sCust);
        }
        
        public System.Threading.Tasks.Task<string> GetItemQOH2Async(string sUser, string sCust)
        {
            return base.Channel.GetItemQOH2Async(sUser, sCust);
        }
        
        public string SubmitOrder(string sCustNo, string sPO, string sPaymentMethod, string sCCInfo, string sOrderInfo, string sDeliveryPickup, string sUser, string sNotes, int iHoldForReview, string sOrderType)
        {
            return base.Channel.SubmitOrder(sCustNo, sPO, sPaymentMethod, sCCInfo, sOrderInfo, sDeliveryPickup, sUser, sNotes, iHoldForReview, sOrderType);
        }
        
        public System.Threading.Tasks.Task<string> SubmitOrderAsync(string sCustNo, string sPO, string sPaymentMethod, string sCCInfo, string sOrderInfo, string sDeliveryPickup, string sUser, string sNotes, int iHoldForReview, string sOrderType)
        {
            return base.Channel.SubmitOrderAsync(sCustNo, sPO, sPaymentMethod, sCCInfo, sOrderInfo, sDeliveryPickup, sUser, sNotes, iHoldForReview, sOrderType);
        }
        
        public string SubmitOrder2(string sCustNo, string sPO, string sPaymentMethod, string sCCInfo, string sOrderInfo, string sDeliveryPickup, string sUser, string sNotes, int iHoldForReview, string sOrderType)
        {
            return base.Channel.SubmitOrder2(sCustNo, sPO, sPaymentMethod, sCCInfo, sOrderInfo, sDeliveryPickup, sUser, sNotes, iHoldForReview, sOrderType);
        }
        
        public System.Threading.Tasks.Task<string> SubmitOrder2Async(string sCustNo, string sPO, string sPaymentMethod, string sCCInfo, string sOrderInfo, string sDeliveryPickup, string sUser, string sNotes, int iHoldForReview, string sOrderType)
        {
            return base.Channel.SubmitOrder2Async(sCustNo, sPO, sPaymentMethod, sCCInfo, sOrderInfo, sDeliveryPickup, sUser, sNotes, iHoldForReview, sOrderType);
        }
        
        public string SubmitRemoteOrder(string sCustNo, string sPO, string sOrderInfo)
        {
            return base.Channel.SubmitRemoteOrder(sCustNo, sPO, sOrderInfo);
        }
        
        public System.Threading.Tasks.Task<string> SubmitRemoteOrderAsync(string sCustNo, string sPO, string sOrderInfo)
        {
            return base.Channel.SubmitRemoteOrderAsync(sCustNo, sPO, sOrderInfo);
        }
        
        public string SubmitReturn(string sCustNo, string sOrderInfo, string sUser, string sNotes)
        {
            return base.Channel.SubmitReturn(sCustNo, sOrderInfo, sUser, sNotes);
        }
        
        public System.Threading.Tasks.Task<string> SubmitReturnAsync(string sCustNo, string sOrderInfo, string sUser, string sNotes)
        {
            return base.Channel.SubmitReturnAsync(sCustNo, sOrderInfo, sUser, sNotes);
        }
        
        public string GetSalespersonCustomers(string sUser)
        {
            return base.Channel.GetSalespersonCustomers(sUser);
        }
        
        public System.Threading.Tasks.Task<string> GetSalespersonCustomersAsync(string sUser)
        {
            return base.Channel.GetSalespersonCustomersAsync(sUser);
        }
        
        public string GetFlyerItemsPDF()
        {
            return base.Channel.GetFlyerItemsPDF();
        }
        
        public System.Threading.Tasks.Task<string> GetFlyerItemsPDFAsync()
        {
            return base.Channel.GetFlyerItemsPDFAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RemotePhoneAppSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.RemotePhoneAppSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RemotePhoneAppSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.229:8070/remotephoneapp.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.RemotePhoneAppSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.229:8070/remotephoneapp.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            RemotePhoneAppSoap,
            
            RemotePhoneAppSoap12,
        }
    }
}
